# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: personaleddiewallnuttesting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: teste-app
service: aws-python # NOTE: update this with your service name


provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
